### ISSUE TITLE
os.rename can not found model-2600

### ISSUE THREAD

**Issue by aloyschen** [jiegzhan/multi-class-text-classification-cnn-rnn#26]
I didn't change any file
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    train_cnn_rnn()
  File "train.py", line 151, in train_cnn_rnn
    os.rename(path, trained_dir + 'best_model.ckpt')
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints_1504000981/model-2600' -> './trained_results_1504000981/best_model.ckpt'

**Comment by aloyschen** [comment]
I have change the code as follow:
logging.critical('Training is complete, testing the best model on x_test and y_test')
saver.save(sess, trained_dir + 'best_model.ckpt')
# Evaluate x_test and y_test
saver.restore(sess, checkpoint_prefix + '-' + str(best_at_step))
